// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnM0tDFZ_4vJQG7IVcnHB9PW6HpOdRS8U',
    appId: '1:57468296080:web:e781041dc5f12eb60eb115',
    messagingSenderId: '57468296080',
    projectId: 'vivieraufba',
    authDomain: 'vivieraufba.firebaseapp.com',
    storageBucket: 'vivieraufba.firebasestorage.app',
    measurementId: 'G-3NSF1W06MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXHbK9GyNiRGE7gE-et_RGvWBteNV-q2U',
    appId: '1:57468296080:android:b78a78220df445f20eb115',
    messagingSenderId: '57468296080',
    projectId: 'vivieraufba',
    storageBucket: 'vivieraufba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEwtDWSocctdvCu1wX5bz3iu1Wb8rsMfI',
    appId: '1:57468296080:ios:7f8a9ae97eb590bb0eb115',
    messagingSenderId: '57468296080',
    projectId: 'vivieraufba',
    storageBucket: 'vivieraufba.firebasestorage.app',
    iosBundleId: 'com.example.projetoViviera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEwtDWSocctdvCu1wX5bz3iu1Wb8rsMfI',
    appId: '1:57468296080:ios:7f8a9ae97eb590bb0eb115',
    messagingSenderId: '57468296080',
    projectId: 'vivieraufba',
    storageBucket: 'vivieraufba.firebasestorage.app',
    iosBundleId: 'com.example.projetoViviera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnM0tDFZ_4vJQG7IVcnHB9PW6HpOdRS8U',
    appId: '1:57468296080:web:17aef1c0ee3f30780eb115',
    messagingSenderId: '57468296080',
    projectId: 'vivieraufba',
    authDomain: 'vivieraufba.firebaseapp.com',
    storageBucket: 'vivieraufba.firebasestorage.app',
    measurementId: 'G-6WLX7VDRK1',
  );
}
